name: gen_form_model docker checker
on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gen_form_model docker checker build image
      id: docker_checker
      run: |
        echo Building Docker image
        build_transcript=$(docker build . --file Dockerfile --tag gen_form_model:latest)
        [[ "$build_transcript" == *"Successfully"* ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
    - name: check on failures
      if: steps.docker_checker.outputs.status == 'failure'
      run: exit 1
